//! A local HTTP server that simulates the ways media hosts behave and
//! misbehave, so downloads can be tested offline and deterministically on
//! every platform. Bodies are generated from a seed (never stored), so any
//! size is available and the expected hash is computable.
//!
//! Routes (`{size}` in bytes):
//!
//! | Path | Behaviour |
//! |---|---|
//! | `/normal/{size}`, `/range/{size}` | 200/206, `Accept-Ranges: bytes`, strong ETag, honours `Range` and `If-Range` |
//! | `/weak-etag/{size}` | like `/range` but with a weak ETag |
//! | `/no-range/{size}` | ignores `Range` (always 200, no `Accept-Ranges`) |
//! | `/no-length/{size}` | chunked transfer, no `Content-Length` |
//! | `/changed-etag/{size}` | the ETag changes on every request (an `If-Range` never matches) |
//! | `/redirect/{status}/{hops}/{size}` | `hops` redirects of `status` (301/302/307/308) ending at `/range/{size}` |
//! | `/redirect-private/{target}` | 302 to `metadata`, `lan` or `loopback` private addresses |
//! | `/status/{code}` | that status (429/503 carry `Retry-After: 1`) |
//! | `/rate-limit/{size}` | first request 429 + `Retry-After: 1`, then `/range` |
//! | `/flaky/{fail}/{size}` | first `fail` requests 503, then `/range` |
//! | `/truncate/{size}/{at}` | declares `size`, sends `at` bytes, then closes |
//! | `/disconnect/{size}/{at}` | declares `size`, sends `at` bytes, then fails the stream |
//! | `/stall/{size}/{after}` | sends `after` bytes, then never sends more |
//! | `/slow/{size}/{bps}` | paced body (`bps` bytes per second) |
//! | `/gzip/{size}` | `Content-Encoding: gzip` header on an unencoded body |
//! | `/content-range-bad/{size}` | 206 with a malformed `Content-Range` |
//! | `/range-wrong-start/{size}` | 206 whose `Content-Range` starts one byte early |
//!
//! Every request is recorded ([`MediaServer::requests`]) and the server
//! tracks the peak number of concurrent bodies per route prefix
//! ([`MediaServer::max_concurrent`]).

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::missing_panics_doc)]

use std::collections::HashMap;
use std::pin::Pin;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Mutex};
use std::task::{Context, Poll};
use std::time::Duration;

use axum::Router;
use axum::body::Body;
use axum::extract::{Path, State};
use axum::http::{HeaderMap, HeaderValue, StatusCode, header};
use axum::response::{IntoResponse, Response};
use axum::routing::get;
use bytes::Bytes;
use futures_util::Stream;
use sha2::{Digest, Sha256};
use tokio_util::sync::CancellationToken;

/// Generated bytes come in blocks of this size (seekable in O(1)).
const BLOCK: u64 = 64 * 1024;

fn seed_for(size: u64) -> u64 {
    // FNV-1a over the decimal size, so equal sizes share content across routes.
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for b in size.to_string().bytes() {
        h ^= u64::from(b);
        h = h.wrapping_mul(0x0100_0000_01b3);
    }
    h
}

fn block(seed: u64, index: u64) -> Vec<u8> {
    let mut x = seed ^ index.wrapping_mul(0x9E37_79B9_7F4A_7C15) ^ 0xD1B5_4A32_D192_ED03;
    let mut out = Vec::with_capacity(usize::try_from(BLOCK).unwrap());
    while (out.len() as u64) < BLOCK {
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        out.extend_from_slice(&x.to_le_bytes());
    }
    out
}

/// The bytes `[start, start + len)` of the generated body of `size` bytes.
#[must_use]
pub fn content_bytes(size: u64, start: u64, len: u64) -> Vec<u8> {
    let seed = seed_for(size);
    let end = (start + len).min(size);
    let mut out = Vec::new();
    let mut pos = start;
    while pos < end {
        let b = block(seed, pos / BLOCK);
        let off = usize::try_from(pos % BLOCK).unwrap();
        let take = usize::try_from((end - pos).min(BLOCK - pos % BLOCK)).unwrap();
        out.extend_from_slice(&b[off..off + take]);
        pos += take as u64;
    }
    out
}

/// SHA-256 (hex) of the generated body of `size` bytes.
#[must_use]
pub fn content_sha256(size: u64) -> String {
    let seed = seed_for(size);
    let mut h = Sha256::new();
    let mut pos = 0u64;
    while pos < size {
        let b = block(seed, pos / BLOCK);
        let take = usize::try_from((size - pos).min(BLOCK)).unwrap();
        h.update(&b[..take]);
        pos += take as u64;
    }
    hex::encode(h.finalize())
}

/// One request as the server saw it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RecordedRequest {
    /// Request path.
    pub path: String,
    /// `Range` header, if sent.
    pub range: Option<String>,
    /// `If-Range` header, if sent.
    pub if_range: Option<String>,
    /// `Accept-Encoding` header, if sent.
    pub accept_encoding: Option<String>,
    /// Every header (lower-case names).
    pub headers: Vec<(String, String)>,
}

impl RecordedRequest {
    /// The requested start offset, when a `Range: bytes=N-` was sent.
    #[must_use]
    pub fn range_start(&self) -> Option<u64> {
        self.range
            .as_deref()?
            .strip_prefix("bytes=")?
            .split('-')
            .next()?
            .parse()
            .ok()
    }
}

#[derive(Default)]
struct Shared {
    log: Mutex<Vec<RecordedRequest>>,
    hits: Mutex<HashMap<String, u32>>,
    concurrent: Mutex<HashMap<String, (usize, usize)>>,
    total: Mutex<(usize, usize)>,
    etag_counter: AtomicU64,
}

impl Shared {
    fn record(&self, path: &str, headers: &HeaderMap) -> u32 {
        let get = |n: &str| {
            headers
                .get(n)
                .and_then(|v| v.to_str().ok())
                .map(str::to_owned)
        };
        self.log.lock().unwrap().push(RecordedRequest {
            path: path.to_owned(),
            range: get("range"),
            if_range: get("if-range"),
            accept_encoding: get("accept-encoding"),
            headers: headers
                .iter()
                .map(|(k, v)| {
                    (
                        k.as_str().to_owned(),
                        v.to_str().unwrap_or("<binary>").to_owned(),
                    )
                })
                .collect(),
        });
        let mut hits = self.hits.lock().unwrap();
        let n = hits.entry(path.to_owned()).or_insert(0);
        *n += 1;
        *n
    }

    fn enter(self: &Arc<Self>, prefix: &str) -> BodyGuard {
        {
            let mut c = self.concurrent.lock().unwrap();
            let e = c.entry(prefix.to_owned()).or_insert((0, 0));
            e.0 += 1;
            e.1 = e.1.max(e.0);
            let mut t = self.total.lock().unwrap();
            t.0 += 1;
            t.1 = t.1.max(t.0);
        }
        BodyGuard {
            shared: Arc::clone(self),
            prefix: prefix.to_owned(),
        }
    }
}

/// Decrements the concurrency counters when the body is dropped (finished
/// or abandoned).
struct BodyGuard {
    shared: Arc<Shared>,
    prefix: String,
}

impl Drop for BodyGuard {
    fn drop(&mut self) {
        let mut c = self.shared.concurrent.lock().unwrap();
        if let Some(e) = c.get_mut(&self.prefix) {
            e.0 = e.0.saturating_sub(1);
        }
        let mut t = self.shared.total.lock().unwrap();
        t.0 = t.0.saturating_sub(1);
    }
}

/// What a generated body does after `send` bytes.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Tail {
    /// Normal end.
    End,
    /// Close the connection without an error frame (declared length not met).
    Close,
    /// Fail the stream.
    Error,
    /// Never send another byte.
    Stall,
}

/// The generated body stream.
struct GenStream {
    seed: u64,
    pos: u64,
    end: u64,
    send_until: u64,
    tail: Tail,
    pace: Option<(u64, Pin<Box<tokio::time::Sleep>>)>,
    _guard: BodyGuard,
    stalled: bool,
    /// Set once the last byte is out: hyper only flushes its write buffer
    /// when the body is not ready, so the tail waits a moment before
    /// ending or failing, otherwise the client would never see the head.
    tail_wait: Option<Pin<Box<tokio::time::Sleep>>>,
}

impl Stream for GenStream {
    type Item = Result<Bytes, std::io::Error>;

    fn poll_next(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        if self.pos >= self.send_until {
            if self.tail != Tail::End {
                if self.tail_wait.is_none() {
                    self.tail_wait = Some(Box::pin(tokio::time::sleep(Duration::from_millis(50))));
                }
                if let Some(w) = self.tail_wait.as_mut()
                    && w.as_mut().poll(cx).is_pending()
                {
                    return Poll::Pending;
                }
            }
            return match self.tail {
                Tail::End | Tail::Close => Poll::Ready(None),
                Tail::Error => {
                    if self.stalled {
                        return Poll::Ready(None);
                    }
                    self.stalled = true;
                    Poll::Ready(Some(Err(std::io::Error::other("injected disconnect"))))
                }
                Tail::Stall => Poll::Pending,
            };
        }
        if let Some((_, sleep)) = self.pace.as_mut()
            && sleep.as_mut().poll(cx).is_pending()
        {
            return Poll::Pending;
        }
        let chunk_len = match self.pace {
            Some((bps, _)) => (bps / 10).clamp(1, BLOCK),
            None => BLOCK - self.pos % BLOCK,
        }
        .min(self.send_until - self.pos);
        let bytes = content_bytes(self.end, self.pos, chunk_len);
        self.pos += bytes.len() as u64;
        if let Some((_, sleep)) = self.pace.as_mut() {
            sleep
                .as_mut()
                .reset(tokio::time::Instant::now() + Duration::from_millis(100));
        }
        Poll::Ready(Some(Ok(Bytes::from(bytes))))
    }
}

#[derive(Clone)]
struct AppState {
    shared: Arc<Shared>,
}

/// How a route answers a byte request.
struct Serve {
    size: u64,
    accept_ranges: bool,
    honour_range: bool,
    etag: Option<String>,
    declare_length: bool,
    send_until: Option<u64>,
    tail: Tail,
    pace: Option<u64>,
    extra: Vec<(&'static str, String)>,
    content_range_override: Option<String>,
}

impl Serve {
    fn plain(size: u64) -> Self {
        Self {
            size,
            accept_ranges: true,
            honour_range: true,
            etag: Some(format!("\"gen-{size}\"")),
            declare_length: true,
            send_until: None,
            tail: Tail::End,
            pace: None,
            extra: Vec::new(),
            content_range_override: None,
        }
    }
}

fn respond(state: &AppState, prefix: &str, headers: &HeaderMap, s: Serve) -> Response {
    let range = headers
        .get(header::RANGE)
        .and_then(|v| v.to_str().ok())
        .and_then(|v| v.strip_prefix("bytes="))
        .and_then(|v| v.split('-').next())
        .and_then(|v| v.parse::<u64>().ok());
    let if_range = headers.get(header::IF_RANGE).and_then(|v| v.to_str().ok());
    let validator_ok = match (if_range, &s.etag) {
        (Some(v), Some(e)) => v == e,
        (Some(_), None) => false,
        (None, _) => true,
    };
    let (status, start) = match range {
        Some(start) if s.honour_range && validator_ok => {
            if start >= s.size {
                let mut r = Response::new(Body::empty());
                *r.status_mut() = StatusCode::RANGE_NOT_SATISFIABLE;
                r.headers_mut().insert(
                    header::CONTENT_RANGE,
                    HeaderValue::from_str(&format!("bytes */{}", s.size)).unwrap(),
                );
                return r;
            }
            (StatusCode::PARTIAL_CONTENT, start)
        }
        _ => (StatusCode::OK, 0),
    };
    let send_until = s.send_until.map_or(s.size, |n| n.min(s.size).max(start));
    let stream = GenStream {
        seed: seed_for(s.size),
        pos: start,
        end: s.size,
        send_until,
        tail: s.tail,
        pace: s
            .pace
            .map(|bps| (bps, Box::pin(tokio::time::sleep(Duration::ZERO)))),
        _guard: state.shared.enter(prefix),
        stalled: false,
        tail_wait: None,
    };
    let _ = stream.seed;
    let mut r = Response::new(Body::from_stream(stream));
    *r.status_mut() = status;
    let h = r.headers_mut();
    h.insert(header::CONTENT_TYPE, HeaderValue::from_static("audio/mpeg"));
    if s.accept_ranges {
        h.insert(header::ACCEPT_RANGES, HeaderValue::from_static("bytes"));
    }
    if let Some(e) = &s.etag {
        h.insert(header::ETAG, HeaderValue::from_str(e).unwrap());
    }
    h.insert(
        header::LAST_MODIFIED,
        HeaderValue::from_static("Wed, 17 Sep 2026 10:00:00 GMT"),
    );
    if s.declare_length {
        h.insert(
            header::CONTENT_LENGTH,
            HeaderValue::from_str(&(s.size - start).to_string()).unwrap(),
        );
    }
    if status == StatusCode::PARTIAL_CONTENT {
        let cr = s
            .content_range_override
            .clone()
            .unwrap_or_else(|| format!("bytes {}-{}/{}", start, s.size - 1, s.size));
        h.insert(header::CONTENT_RANGE, HeaderValue::from_str(&cr).unwrap());
    }
    for (k, v) in s.extra {
        h.insert(
            header::HeaderName::from_static(k),
            HeaderValue::from_str(&v).unwrap(),
        );
    }
    r
}

fn status_response(code: u16) -> Response {
    let status = StatusCode::from_u16(code).unwrap_or(StatusCode::INTERNAL_SERVER_ERROR);
    let mut r = (status, format!("status {code}")).into_response();
    if code == 429 || code == 503 {
        r.headers_mut()
            .insert(header::RETRY_AFTER, HeaderValue::from_static("1"));
    }
    r
}

type S = State<AppState>;

async fn range(State(st): S, Path(size): Path<u64>, headers: HeaderMap) -> Response {
    st.shared.record(&format!("/range/{size}"), &headers);
    respond(&st, "range", &headers, Serve::plain(size))
}

async fn normal(State(st): S, Path(size): Path<u64>, headers: HeaderMap) -> Response {
    st.shared.record(&format!("/normal/{size}"), &headers);
    respond(&st, "normal", &headers, Serve::plain(size))
}

async fn weak_etag(State(st): S, Path(size): Path<u64>, headers: HeaderMap) -> Response {
    st.shared.record(&format!("/weak-etag/{size}"), &headers);
    respond(
        &st,
        "weak-etag",
        &headers,
        Serve {
            etag: Some(format!("W/\"gen-{size}\"")),
            ..Serve::plain(size)
        },
    )
}

async fn no_range(State(st): S, Path(size): Path<u64>, headers: HeaderMap) -> Response {
    st.shared.record(&format!("/no-range/{size}"), &headers);
    respond(
        &st,
        "no-range",
        &headers,
        Serve {
            accept_ranges: false,
            honour_range: false,
            ..Serve::plain(size)
        },
    )
}

async fn no_length(State(st): S, Path(size): Path<u64>, headers: HeaderMap) -> Response {
    st.shared.record(&format!("/no-length/{size}"), &headers);
    respond(
        &st,
        "no-length",
        &headers,
        Serve {
            accept_ranges: false,
            honour_range: false,
            declare_length: false,
            etag: None,
            ..Serve::plain(size)
        },
    )
}

async fn changed_etag(State(st): S, Path(size): Path<u64>, headers: HeaderMap) -> Response {
    st.shared.record(&format!("/changed-etag/{size}"), &headers);
    let n = st.shared.etag_counter.fetch_add(1, Ordering::SeqCst);
    respond(
        &st,
        "changed-etag",
        &headers,
        Serve {
            etag: Some(format!("\"gen-{size}-{n}\"")),
            ..Serve::plain(size)
        },
    )
}

async fn redirect(
    State(st): S,
    Path((status, hops, size)): Path<(u16, u32, u64)>,
    headers: HeaderMap,
) -> Response {
    st.shared
        .record(&format!("/redirect/{status}/{hops}/{size}"), &headers);
    let target = if hops <= 1 {
        format!("/range/{size}")
    } else {
        format!("/redirect/{status}/{}/{size}", hops - 1)
    };
    let mut r = Response::new(Body::empty());
    *r.status_mut() = StatusCode::from_u16(status).unwrap_or(StatusCode::FOUND);
    r.headers_mut()
        .insert(header::LOCATION, HeaderValue::from_str(&target).unwrap());
    r
}

async fn redirect_private(
    State(st): S,
    Path(target): Path<String>,
    headers: HeaderMap,
) -> Response {
    st.shared
        .record(&format!("/redirect-private/{target}"), &headers);
    let loc = match target.as_str() {
        "metadata" => "http://169.254.169.254/latest/meta-data/",
        "lan" => "http://10.0.0.1/secret.mp3",
        _ => "http://127.0.0.1:1/secret.mp3",
    };
    let mut r = Response::new(Body::empty());
    *r.status_mut() = StatusCode::FOUND;
    r.headers_mut()
        .insert(header::LOCATION, HeaderValue::from_static(loc));
    r
}

async fn status(State(st): S, Path(code): Path<u16>, headers: HeaderMap) -> Response {
    st.shared.record(&format!("/status/{code}"), &headers);
    status_response(code)
}

async fn rate_limit(State(st): S, Path(size): Path<u64>, headers: HeaderMap) -> Response {
    let n = st.shared.record(&format!("/rate-limit/{size}"), &headers);
    if n == 1 {
        return status_response(429);
    }
    respond(&st, "rate-limit", &headers, Serve::plain(size))
}

async fn flaky(State(st): S, Path((fail, size)): Path<(u32, u64)>, headers: HeaderMap) -> Response {
    let n = st.shared.record(&format!("/flaky/{fail}/{size}"), &headers);
    if n <= fail {
        return status_response(503);
    }
    respond(&st, "flaky", &headers, Serve::plain(size))
}

async fn truncate(
    State(st): S,
    Path((size, at)): Path<(u64, u64)>,
    headers: HeaderMap,
) -> Response {
    st.shared
        .record(&format!("/truncate/{size}/{at}"), &headers);
    respond(
        &st,
        "truncate",
        &headers,
        Serve {
            send_until: Some(at),
            tail: Tail::Close,
            ..Serve::plain(size)
        },
    )
}

async fn disconnect(
    State(st): S,
    Path((size, at)): Path<(u64, u64)>,
    headers: HeaderMap,
) -> Response {
    st.shared
        .record(&format!("/disconnect/{size}/{at}"), &headers);
    respond(
        &st,
        "disconnect",
        &headers,
        Serve {
            send_until: Some(at),
            tail: Tail::Error,
            ..Serve::plain(size)
        },
    )
}

async fn stall(
    State(st): S,
    Path((size, after)): Path<(u64, u64)>,
    headers: HeaderMap,
) -> Response {
    st.shared
        .record(&format!("/stall/{size}/{after}"), &headers);
    respond(
        &st,
        "stall",
        &headers,
        Serve {
            send_until: Some(after),
            tail: Tail::Stall,
            ..Serve::plain(size)
        },
    )
}

async fn slow(State(st): S, Path((size, bps)): Path<(u64, u64)>, headers: HeaderMap) -> Response {
    st.shared.record(&format!("/slow/{size}/{bps}"), &headers);
    respond(
        &st,
        "slow",
        &headers,
        Serve {
            pace: Some(bps.max(10)),
            ..Serve::plain(size)
        },
    )
}

async fn gzip(State(st): S, Path(size): Path<u64>, headers: HeaderMap) -> Response {
    st.shared.record(&format!("/gzip/{size}"), &headers);
    respond(
        &st,
        "gzip",
        &headers,
        Serve {
            extra: vec![("content-encoding", "gzip".to_owned())],
            ..Serve::plain(size)
        },
    )
}

async fn content_range_bad(State(st): S, Path(size): Path<u64>, headers: HeaderMap) -> Response {
    st.shared
        .record(&format!("/content-range-bad/{size}"), &headers);
    respond(
        &st,
        "content-range-bad",
        &headers,
        Serve {
            content_range_override: Some("bytes garbage".to_owned()),
            ..Serve::plain(size)
        },
    )
}

async fn range_wrong_start(State(st): S, Path(size): Path<u64>, headers: HeaderMap) -> Response {
    st.shared
        .record(&format!("/range-wrong-start/{size}"), &headers);
    let start = headers
        .get(header::RANGE)
        .and_then(|v| v.to_str().ok())
        .and_then(|v| v.strip_prefix("bytes="))
        .and_then(|v| v.split('-').next())
        .and_then(|v| v.parse::<u64>().ok())
        .unwrap_or(0);
    respond(
        &st,
        "range-wrong-start",
        &headers,
        Serve {
            content_range_override: Some(format!(
                "bytes {}-{}/{size}",
                start.saturating_sub(1),
                size - 1
            )),
            ..Serve::plain(size)
        },
    )
}

/// The running scenario server.
pub struct MediaServer {
    base: String,
    shared: Arc<Shared>,
    stop: CancellationToken,
    task: Option<tokio::task::JoinHandle<()>>,
}

impl std::fmt::Debug for MediaServer {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("MediaServer")
            .field("base", &self.base)
            .finish_non_exhaustive()
    }
}

impl MediaServer {
    /// Starts the server on an ephemeral loopback port.
    pub async fn start() -> Self {
        let shared = Arc::new(Shared::default());
        let state = AppState {
            shared: Arc::clone(&shared),
        };
        let app = Router::new()
            .route("/range/{size}", get(range))
            .route("/normal/{size}", get(normal))
            .route("/weak-etag/{size}", get(weak_etag))
            .route("/no-range/{size}", get(no_range))
            .route("/no-length/{size}", get(no_length))
            .route("/changed-etag/{size}", get(changed_etag))
            .route("/redirect/{status}/{hops}/{size}", get(redirect))
            .route("/redirect-private/{target}", get(redirect_private))
            .route("/status/{code}", get(status))
            .route("/rate-limit/{size}", get(rate_limit))
            .route("/flaky/{fail}/{size}", get(flaky))
            .route("/truncate/{size}/{at}", get(truncate))
            .route("/disconnect/{size}/{at}", get(disconnect))
            .route("/stall/{size}/{after}", get(stall))
            .route("/slow/{size}/{bps}", get(slow))
            .route("/gzip/{size}", get(gzip))
            .route("/content-range-bad/{size}", get(content_range_bad))
            .route("/range-wrong-start/{size}", get(range_wrong_start))
            .with_state(state);
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0")
            .await
            .expect("bind loopback");
        let base = format!("http://{}", listener.local_addr().expect("addr"));
        let stop = CancellationToken::new();
        let stop2 = stop.clone();
        let task = tokio::spawn(async move {
            let _ = axum::serve(listener, app)
                .with_graceful_shutdown(async move { stop2.cancelled().await })
                .await;
        });
        Self {
            base,
            shared,
            stop,
            task: Some(task),
        }
    }

    /// `http://127.0.0.1:<port>`.
    #[must_use]
    pub fn base(&self) -> &str {
        &self.base
    }

    /// A full URL for a path (`/range/1000`).
    #[must_use]
    pub fn url(&self, path: &str) -> String {
        format!("{}{path}", self.base)
    }

    /// Every request so far.
    #[must_use]
    pub fn requests(&self) -> Vec<RecordedRequest> {
        self.shared.log.lock().unwrap().clone()
    }

    /// Requests to one exact path.
    #[must_use]
    pub fn requests_for(&self, path: &str) -> Vec<RecordedRequest> {
        self.requests()
            .into_iter()
            .filter(|r| r.path == path)
            .collect()
    }

    /// Requests to one exact path.
    #[must_use]
    pub fn hits(&self, path: &str) -> u32 {
        self.shared
            .hits
            .lock()
            .unwrap()
            .get(path)
            .copied()
            .unwrap_or(0)
    }

    /// Peak number of bodies in flight at once for a route prefix (`range`).
    #[must_use]
    pub fn max_concurrent(&self, prefix: &str) -> usize {
        self.shared
            .concurrent
            .lock()
            .unwrap()
            .get(prefix)
            .map_or(0, |e| e.1)
    }

    /// Peak number of bodies in flight at once across every route.
    #[must_use]
    pub fn max_concurrent_total(&self) -> usize {
        self.shared.total.lock().unwrap().1
    }

    /// Forgets the request log, hit counts and peaks.
    pub fn reset(&self) {
        self.shared.log.lock().unwrap().clear();
        self.shared.hits.lock().unwrap().clear();
        for e in self.shared.concurrent.lock().unwrap().values_mut() {
            e.1 = e.0;
        }
        let mut t = self.shared.total.lock().unwrap();
        t.1 = t.0;
    }

    /// Stops the server.
    pub async fn stop(mut self) {
        self.stop.cancel();
        if let Some(t) = self.task.take() {
            let _ = tokio::time::timeout(Duration::from_secs(5), t).await;
        }
    }
}

impl Drop for MediaServer {
    fn drop(&mut self) {
        self.stop.cancel();
        if let Some(t) = self.task.take() {
            t.abort();
        }
    }
}
